### ISSUE TITLE
[Suggestion] [LazyLoadChannels]

### ISSUE THREAD

**Issue by DeCat4** [Skamt/BDAddons#16]
If by any chance you plan on further expanding this plugin it would be nice to have some configurability for loaded channels, a slider or a number you can set to control how many images, reactions and emotes can be loaded, i don't know how discord handles the loading but it would be nice to lower the amount of images & reactions are loaded in a specific channel because BD seems to take ages loading servers sometimes just because there's a lot of reactions.

**Comment by Skamt** [comment]
I don't have any plans to do any major upgrading, maybe minor changes.

blocking channels from loading just because you navigate servers seems enough to me, You have control to load a channel or not instead of it being automatic just by browsing servers.

I feel like anymore enhancement would not be worth the time (*given that it doesn't break some obscure feature*)

Point is when you click `load channel` it's a per user action and you are prepared for the lag should there be any. i feel like that's enough
