### ISSUE TITLE
SVG icon are not on the "left side"

### ISSUE THREAD

**Issue by Azzuray** [Skamt/BDAddons#2]
Hi, i just noticed you updated your pluggin but i dont remember when does this came , looking from your exemple i can see your "show profile avatar being on the left side of the carrousel but on the last rev its back on top of the "Nitro badge" thingy 

 some exemples  : 

![image](https://user-images.githubusercontent.com/76765834/196339486-ee630f80-a421-4cc2-803e-b6625ecc4479.png)
![image](https://user-images.githubusercontent.com/76765834/196339882-f0f06558-a2d4-44e7-a97e-9ef7289f8c53.png)

**Comment by Skamt** [comment]
This has been fixed, thanks for the feedback.
Keep in mind none of the plugins in this repo are made official and aren't meant to be used by anyone just yet. all are still a work-in-progress. 

You may want to ping me in BetterDiscord support server instead of creating an issue, at least until the plugins have been released.
