### ISSUE TITLE
Request feature for LazyLoadChannels

### ISSUE THREAD

**Issue by miyuki-ts** [Skamt/BDAddons#27]
https://betterdiscord.app/plugin/LazyLoadChannels

this betterdiscord plugin, i am requesting a feature, where i can click on a bottom to unload it so discord can perform faster, forexample navigating through many dms or discord server. for where the bottom should be placed, either at far down or at top somewhere.

forexample on big discord server, i had to restart my discord to even let me go anywhere because of performance and the loading, because there is so many ressource that it need to load.

**Comment by Skamt** [comment]
although this might seem to be related, it's actually not, the purpose of this plugin is to stop channels from loading automatically, it also prevents messages from being fetched, when you load a channel you can't undo the fetching part at least.


unloading a channel will you give close to nothing in performance because all you can do is release the memory held by all the messages, discord already does that when you switch between accounts, You can test that and see.

**Comment by Skamt** [comment]
I'm running BD with 9 plugins on a very low end PC and i never experience any lag, that's probably because I'm part of about 4 servers that are not too active.

So best guess you're a heavy discord user, If you have a lot of servers, a lot of DMs etc your discord is bound to be slow, maybe try to reduce those numbers.

Discord doesn't keep more than 200 messages cached per channel, so if you open a lot of channels sure that could contribute to it.

It would be very difficult for me to test the actual performance difference of this feature that is mainly why i probably won't add it

*if you're using the new 64bit version try going back to 32bit*
