### ISSUE TITLE
[Request] Copy Image Link Compatibility

### ISSUE THREAD

**Issue by Lagomorpheus** [Skamt/BDAddons#6]
Please make the plugin work with imageutilities, the button overlaps the new copy image button from that plugin

**Comment by Skamt** [comment]
You can think of **CopyImageLink** as a simpler version of **ImageUtilities**, Im not sure why you need both installed really, I made it as a helper for **ViewProfilePictures** so that users can copy links, For normal images you right click and then choose Copy link.
It seems pointless to make it compatible with a plugin that already adds more functionalities than this one.

**Comment by Skamt** [comment]
closing this for lack of communication.
